name: Auto Translate

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

permissions: {}

jobs:
  translate:
    name: 'Trigger Auto-Translate Workflow'
    permissions:
      contents: write
      pull-requests: write
    uses: newfold-labs/workflows/.github/workflows/auto-translate.yml@main
    with:
      text_domain: 'wp-plugin-bluehost'
    secrets:
      TRANSLATOR_API_KEY: ${{ secrets.TRANSLATOR_API_KEY }}
      NEWFOLD_ACCESS_TOKEN: ${{ secrets.NEWFOLD_ACCESS_TOKEN }}
