name: Auto Translate

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      text_domain:
        description: "Text domain (Defaults to repository name if text domain is missing)"
        required: false
        default: ""

permissions:
  contents: write
  pull-requests: write

jobs:
  translate:
    uses: newfold-labs/workflows/.github/workflows/auto-translate.yml@main
    with:
      text_domain: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.text_domain || 'wp-plugin-bluehost' }}
    secrets:
      TRANSLATOR_API_KEY: ${{ secrets.TRANSLATOR_API_KEY }}
      NEWFOLD_ACCESS_TOKEN: ${{ secrets.NEWFOLD_ACCESS_TOKEN }}
