name: PHP Lint

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/PRESS0-4271-reusable-workflow-added   # remove after testing
    paths: [ '**.php' ]
  pull_request:
    branches: [ main ]
    paths: [ '**.php' ]

permissions:
  contents: read

jobs:
  php-lint:
    uses: newfold-labs/workflows/.github/workflows/reusable-php-lint.yml@93e85acfbf997f27409792f1f54dabcf890cda6d
    with:
      php-version: '8.1'