name: Scan & Lint Workflow Files

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
    paths:
      - '**.yml'
  pull_request:
    types: [ opened, edited, synchronize, reopened, ready_for_review ]
    paths:
      - '**.yml'

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name for pull requests
  # or the commit hash for any other events.
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

# Disable permissions for all available scopes by default.
# Any needed permissions should be configured at the job level.
permissions: {}

jobs:
  lint:
    name: Scan & lint workflow files
    permissions:
      security-events: write
      actions: read
      contents: read
    uses: newfold-labs/workflows/.github/workflows/reusable-workflow-lint.yml@main
